#!/bin/sh

BASE_DIR="$1"
TARGET_DIR="$2"

# TODO: Consider all files from the base dir as deployable.
#       Provide a simple space sperated list of files to be
#       ignored.
# HOME_CONF_IGNORE=".git LICENSE README[^\s]*"
# SED_IGNORE=$(sed -r "s/$HOME_CONF_IGNORE//g")
# HOME_CONF_FILES=$(ls -A $BASE_DIR)
# echo "$HOME_CONF_FILES"
# HOME_CONF_IGNORE=".git LICENSE README.md"

HOME_CONF_DIRS="bin .bash_conf.d"
HOME_CONF_FILES=".bash_custom .bash_misc bin/ffpog .gitconfig\
 .emacs .git_commit_template .gitignore_global .tmux.conf"

mkdir="mkdir"
link="ln -s"

if [ "Z$BASE_DIR" = "Z" ]; then
    BASE_DIR="$(pwd)"
fi

if [ "Z$TARGET_DIR" = "Z" ]; then
    TARGET_DIR="$HOME"
fi


if [ ! -r "$BASE_DIR" ]; then
    echo "base dir does not exist or is not readable"
    exit 1
fi

if [ ! -w "$TARGET_DIR" ]; then
    echo "target dir does not exist or is not writeable"
    exit 1
fi

for dir in $HOME_CONF_DIRS; do
    if [ ! -w "$TARGET_DIR/$dir" ]; then
        $mkdir "$TARGET_DIR/$dir"
    else
        echo "dir already exists: $TARGET_DIR/$dir"
    fi
done

for file in $HOME_CONF_FILES; do
    if [ ! -f "$TARGET_DIR/$file" ]; then
        $link "$BASE_DIR/$file" "$TARGET_DIR/$file"
    else
        echo "file already exists: $TARGET_DIR/$file"
    fi 
done

